name: mep_dictionary
description: U HokeSein Myanmar-English-Pali Dictionary

publish_to: 'none' 
version: 1.2.1+5

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.2.4+1
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  # substring_highlight: ^1.0.33
  easy_rich_text: ^2.1.0
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.3.1
  backdrop: ^0.9.1
  motion_toast: ^2.10.0
  url_launcher: ^6.3.0
  super_sliver_list: ^0.4.1
  context_menus: ^2.0.0+1
  provider: ^6.1.2
  # riching_text: ^0.1.1

dev_dependencies:
  build_runner: ^2.1.2
  icons_launcher: ^2.0.5
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  flutter_native_splash: ^2.4.1
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0

flutter_icons:
  android: true
  ios: false
  macos: true
  windows: true
  linux: true
  image_path: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/database/mep.db
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansMyanmar
      fonts:
        - asset: assets/fonts/NotoSansMyanmar-Regular.otf
        - asset: assets/fonts/NotoSansMyanmar-Bold.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
